/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.variableproductions.melee;

import java.util.Random;

/**
 *
 * @author geofgibson
 */
public class NPCCard extends javax.swing.JFrame {
    //MLMonster myMonster = new MLMonster();
    Random rand;
    
    /**
     * Creates new form NPCCard
     */
    public NPCCard() {
        initComponents();
        npcNameField.setText(JavaMelee.myController.myMonster.name);
        npcStrengthField.setText(Integer.toString(JavaMelee.myController.myMonster.strength));
        npcDexterityField.setText(Integer.toString(JavaMelee.myController.myMonster.dexterity));
        npcMovementField.setText(Integer.toString(JavaMelee.myController.myMonster.movementAllowance));
        npcArmourNameField.setText(JavaMelee.myController.myMonster.armour.name);
        npcArmourHitsField.setText(Integer.toString(JavaMelee.myController.myMonster.armour.hits));
        npcArmourMovementField.setText(Integer.toString(JavaMelee.myController.myMonster.armour.armourMovement));
        npcNormalCombatField.setText(JavaMelee.myController.myMonster.normalCombat.dice);
        npcNormalWeaponField.setText(JavaMelee.myController.myMonster.normalCombat.name);
        npcHTHCombatField.setText(JavaMelee.myController.myMonster.hthCombat.dice);
        npcAdjDexterityField.setText(Integer.toString(JavaMelee.myController.myMonster.adjDX));
        if (JavaMelee.myController.myMonster.index == 3) {
            dxLabel.setText("To Hit Adj:");
            npcAdjDexterityField.setText(Integer.toString(JavaMelee.myController.myMonster.armour.dxAdj));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        npcNameField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        npcStrengthField = new javax.swing.JLabel();
        npcDexterityField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        npcMovementField = new javax.swing.JLabel();
        npcArmourNameField = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        npcArmourHitsField = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        npcArmourMovementField = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        npcNormalCombatField = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        npcHTHCombatField = new javax.swing.JLabel();
        dxLabel = new javax.swing.JLabel();
        npcAdjDexterityField = new javax.swing.JLabel();
        npcNormalWeaponField = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 400));

        jLabel4.setText("NPC Name:");

        npcNameField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcNameField.setText("<default>");

        jLabel5.setText("Strength:");

        jLabel6.setText("Dexterity:");

        npcStrengthField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcStrengthField.setText("<default>");

        npcDexterityField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcDexterityField.setText("<default>");

        jLabel7.setText("Movement:");

        npcMovementField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcMovementField.setText("<default>");

        npcArmourNameField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcArmourNameField.setText("<default>");

        jLabel8.setText("Armour:");

        npcArmourHitsField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcArmourHitsField.setText("<default>");

        jLabel9.setText("Armour Hits:");

        jLabel10.setText("Adjusted Movement:");

        npcArmourMovementField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcArmourMovementField.setText("<default>");

        jLabel11.setText("Normal Combat:");

        npcNormalCombatField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcNormalCombatField.setText("<default>");

        jLabel12.setText("HTH Combat:");

        npcHTHCombatField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcHTHCombatField.setText("<default>");

        dxLabel.setText("Adj Dexterity:");

        npcAdjDexterityField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcAdjDexterityField.setText("<default>");

        npcNormalWeaponField.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        npcNormalWeaponField.setText("<default>");

        jLabel13.setText("Normal Weapon:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcNameField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcStrengthField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcDexterityField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcMovementField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcArmourNameField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcArmourMovementField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcNormalCombatField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcHTHCombatField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(npcNormalWeaponField)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dxLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(npcAdjDexterityField)
                    .addComponent(npcArmourHitsField))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(npcNameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcStrengthField)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcDexterityField)
                    .addComponent(jLabel6)
                    .addComponent(npcAdjDexterityField)
                    .addComponent(dxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcMovementField)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcArmourNameField)
                    .addComponent(jLabel8)
                    .addComponent(npcArmourHitsField)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcArmourMovementField)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcNormalCombatField)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcNormalWeaponField)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcHTHCombatField)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dxLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel npcAdjDexterityField;
    private javax.swing.JLabel npcArmourHitsField;
    private javax.swing.JLabel npcArmourMovementField;
    private javax.swing.JLabel npcArmourNameField;
    private javax.swing.JLabel npcDexterityField;
    private javax.swing.JLabel npcHTHCombatField;
    private javax.swing.JLabel npcMovementField;
    private javax.swing.JLabel npcNameField;
    private javax.swing.JLabel npcNormalCombatField;
    private javax.swing.JLabel npcNormalWeaponField;
    private javax.swing.JLabel npcStrengthField;
    // End of variables declaration//GEN-END:variables
}
